import React from "react";
import SideMenu from "../SideMenu/SideMenu";
import Head from "next/head";

const Layout = ({
  open,
  drawerClose,
  drawerOpen,
  children,
}: {
  open: boolean;
  drawerClose: any;
  drawerOpen: any;
  children: any;
}) => {
  // const [open, setOpen] = React.useState(true);
  return (
    <>
      <Head>
        <title>Clockify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideMenu drawerOpen={drawerOpen} drawerClose={drawerClose} open={open} />
      <main className={open ? "sidebar--open" : "sidebar--closed"}>
        {children}
      </main>
    </>
  );
};

export default Layout;
