# Generated by Django 4.1.5 on 2023-03-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
