# Generated by Django 4.2b1 on 2023-06-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0021_alter_user_options_project_created_project_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_record', to='workspace.project'),
        ),
    ]
