# Generated by Django 4.2b1 on 2023-09-12 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROJECT_CREATED', 'project created'), ('PROJECT_DONE', 'project done'), ('TASK_CREATED', 'task created'), ('TASK_DONE', 'task done')], max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
