# Generated by Django 4.2b1 on 2023-09-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
