# Generated by Django 4.2b1 on 2023-10-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_created_notification_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
