# Generated by Django 4.2b1 on 2023-10-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notification',),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='task_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low'), (0, 'Info')], default=0),
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('task_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notification',),
        ),
    ]
