# Generated by Django 4.2b1 on 2023-10-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_action_notification_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='task_name',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('CREATED', 'created'), ('DELETED', 'deleted'), ('UPDATE', 'updated')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROJECT', 'project'), ('TASK', 'task')], max_length=36),
        ),
    ]
