# Generated by Django 4.2b1 on 2023-10-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
