# Generated by Django 4.2b1 on 2023-10-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_target_id_notification_target_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target_title',
            new_name='target_name',
        ),
    ]
